# All the actions will be executed only if the commit happens on main branch
name: CI-Branch
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  reuse:
    uses: B60-CloudDevOps/roboshop-github-actions/.github/workflows/ci-branch.yml@main
